defaults: &defaults
    working_directory: /tmp/tacoshop
    docker:
        - image: ubuntu

version: 2
jobs:
    install_dependencies:
        <<: *defaults
        docker:
            - image: ubuntu
        steps:
            - checkout
            - run: mkdir -p /tmp/tacoshop/bin
            - run:
                name: download-architect
                command: |
                    apt update && apt install -y --no-install-recommends ca-certificates wget curl git
                    wget $(curl -sS https://api.github.com/repos/giantswarm/architect/releases/latest | grep browser_download_url | head -n 1 | cut -d '"' -f 4) -O /tmp/tacoshop/bin/architect
                    chmod +x /tmp/tacoshop/bin/architect
                    /tmp/tacoshop/bin/architect version
            - persist_to_workspace:
                root: /tmp/tacoshop/bin
                paths:
                    - architect

    build:
        <<: *defaults
        steps:
            - run: "apt update && apt install -y --no-install-recommends ca-certificates git"
            - attach_workspace:
                at: /tmp/tacoshop/bin
            - run:
                command: |
                    /tmp/tacoshop/bin/architect --organisation=fgimenez build
    deploy:
        <<: *defaults
        steps:
            - run: "apt update && apt install -y --no-install-recommends ca-certificates git"
            - attach_workspace:
                at: /tmp/tacoshop/bin
            - run:
                command: |
                    /tmp/tacoshop/bin/architect --organisation=fgimenez deploy

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - install_dependencies
            - build:
                    requires:
                        - install_dependencies
            - deploy:
                    requires:
                        - build
                    filters:
                        branches:
                            only: master
