apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tacoshop
  labels:
    app: tacoshop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tacoshop
    spec:
      containers:
        - name: tacoshop
          image: quay.io/fgimenez/tacoshop:{{ .SHA }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
