apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tacoshop
  labels:
    app: tacoshop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tacoshop
    spec:
      containers:
        - name: tacoshop
          image: quay.io/fgimenez/tacoshop:{{ .SHA }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /home.thml
              port: 8080
          readinessProbe:
            httpGet:
              path: /home.html
              port: 8080
